Web Design Programming/FinalAssignment/FinalAssignment/Models/GenAI.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FinalAssignment.Models
{
    public class GenAI
    {
        public int Id { get; set; }
        [Display(Name = "Gen AI Name")]
        public string GenAIName { get; set; }
        [Display(Name = "Summary")]
        public string Summary { get; set; }

        [Display(Name = "Image File")]
        [ValidateNever]
        public string ImageFilename { get; set; }

        [Display(Name = "Anchor Link")]
        [ValidateNever]
        public string AnchorLink { get; set; }
        [Display(Name = "Like")]
        public int Like { get; set; }
    }
}

Web Design Programming/FinalAssignment/FinalAssignment/Controllers/GenAIsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalAssignment.Data;
using FinalAssignment.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Routing.Constraints;
using System.Data;
using System.Text.Json;

namespace FinalAssignment.Controllers
{
    public class GenAIsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public GenAIsController(ApplicationDbContext context, IHostingEnvironment hostingEnv)
        {
            _context = context;
            _hostingEnv = hostingEnv;
        }

        public async Task<IActionResult> IncreaseLike(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var genAI = await _context.GenAI.FindAsync(id);
            if (genAI == null)
            {
                return NotFound();
            }
            
            var value = HttpContext.Session.GetString(genAI.GenAIName);
            bool val = value == null ? false : JsonSerializer.Deserialize<bool>(value);


            if (ModelState.IsValid && (val == false))
            {
                try
                {
                    HttpContext.Session.SetString(genAI.GenAIName, JsonSerializer.Serialize(true));
                    genAI.Like++;
                    _context.Update(genAI);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenAIExists(genAI.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: GenAIs
        public async Task<IActionResult> Index()
        {
              return _context.GenAI != null ? 
                          View(await _context.GenAI.OrderByDescending(i => i.Like).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
        }

        // GET: GenAIs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAI == null)
            {
                return NotFound();
            }

            return View(genAI);
        }

        // GET: GenAIs/Create
        public IActionResult Create()
        {
            GenAI genAI = new GenAI();
            genAI.AnchorLink = "none";
            genAI.ImageFilename = "none";
            return View(genAI);
        }

        // POST: GenAIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GenAIName,Summary")] GenAI genAI, UploadFile uploadFile)
        {
            if(uploadFile.File != null)
            {
                var fileName = Path.GetFileName(uploadFile.File.FileName);
                var fileNameWOExt = Path.GetFileNameWithoutExtension(uploadFile.File.FileName);
                genAI.ImageFilename = fileNameWOExt;
                genAI.AnchorLink = "GenAIs/#" + fileNameWOExt.ToLower();
                var filePath = Path.Combine(_hostingEnv.WebRootPath, "images", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await uploadFile.File.CopyToAsync(fileStream);
                }
            }
            
            if (ModelState.IsValid)
            {
                _context.Add(genAI);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genAI);
        }

        // GET: GenAIs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI.FindAsync(id);
            if (genAI == null)
            {
                return NotFound();
            }
            return View(genAI);
        }

        // POST: GenAIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenAIName,Summary, Like, AnchorLink, ImageFilename, uploadFile")] GenAI genAI, UploadFile uploadFile)
        {
            if (id != genAI.Id)
            {
                return NotFound();
            }
            
            if (uploadFile.File != null)
            {
                var fileName = Path.GetFileName(uploadFile.File.FileName);
                var fileNameWOExt = Path.GetFileNameWithoutExtension(uploadFile.File.FileName);
                genAI.ImageFilename = fileNameWOExt;
                genAI.AnchorLink = "GenAIs/#" + fileNameWOExt.ToLower();
                var filePath = Path.Combine(_hostingEnv.WebRootPath, "images", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await uploadFile.File.CopyToAsync(fileStream);
                }
            }
            else
            {
                ModelState.ClearValidationState("File");
                ModelState.MarkFieldValid("File");
            }
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genAI);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenAIExists(genAI.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genAI);
        }

        // GET: GenAIs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAI == null)
            {
                return NotFound();
            }

            return View(genAI);
        }

        // POST: GenAIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GenAI == null)
            {
                return Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
            }
            var genAI = await _context.GenAI.FindAsync(id);
            if (genAI != null)
            {
                _context.GenAI.Remove(genAI);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenAIExists(int id)
        {
          return (_context.GenAI?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Web Design Programming/FinalAssignment/FinalAssignment/Controllers/HomeController.cs
using FinalAssignment.Data;
using FinalAssignment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace FinalAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.GenAI != null ?
                          View(await _context.GenAI.OrderByDescending(i => i.Like).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Jobs()
        {
            return View();
        }

        public IActionResult GenAI()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web Design Programming/FinalAssignment/FinalAssignment/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<link rel="stylesheet" href="~/css/contact.css"/>

<article>
    <section class="text-center">
        <h1 id="contact-title"> Contact & About </h1>
    </section>
    <section class="row g-5 m-4">
        <!-- HTML -->
        <div class="col-md-4 col-sm-12 col-12">
            <section class="contact-container">
                <h1> Contact Us </h1>
                <p>
                    This website was written by Oliver Witrzens <br/>
                    To get in contact please email u3224776@uni.canberra.edu.au
                </p>
            </section>
        </div>

        <!-- CSS -->
        <div class="col-md-4 col-sm-12 col-12">
            <section class="contact-container">
                <h1> About Us </h1>
                <p>
                    This website provides an introduction to Artificial Intelligence and was created as
                    partial fulfillment of the assessment requirements of Web Design and Programming at the
                    University of Canberra. <br/>
                    This site is built on the ASP.NET CORE framework and employs Bootstrap responsive design
                    techniques.
                </p>
            </section>
        </div>

        <!-- BOOTSTRAP -->
        <div class="col-md-4 col-sm-12 col-12">
            <section class="contact-container">
                <h1> Copyright </h1>
                <p>
                    All images used in this website were downloaded from <a href="https://unsplash.com/">Unsplash</a> <br />
                    The icons for the footer from <a href="https://fontawesome.com/">fontawesome</a>.  <br />
                    The Anton font used for headers from <a href="https://fonts.google.com/">Google Fonts</a>.<br />
                    The AI jobs dataset from <a href="https://ai-jobs.net/">Insights</a>.<br />
                    The Python source from <a href="https://www.kaggle.com/code/sowrabhghosh/data-science-salary-2020-22-analysis">Kaggle</a><br />
                    The Python web based on PyScript from <a href="https://realpython.com/pyscript-python-in-browser/">Real Python</a>.<br />
                </p>
            </section>
        </div>
    </section>
</article>

<script src="~/js/contact.js"></script>

Web Design Programming/FinalAssignment/FinalAssignment/Views/Home/GenAI.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/FinalAssignment.styles.css" asp-append-version="true" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Niconne" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="~/css/elastic-grid.min.css" type="text/css" />
<link rel="stylesheet" href="~/css/genai.css" type="text/css" />


@*<div id="elasticGrid"></div>*@

<div id="genaitools" class="gen-ai-section genai-tools">
    <div>
        <h1 class="genai-titles">
            GenAI Tools
        </h1>
    </div>
    <div id="tools"></div>
    
</div>
<div id="genaiorgs" class="gen-ai-section genai-orgs">
    <div>
        <h1 class="genai-titles">
            GenAI Orgs
        </h1>
    </div>
    <div id="orgs"></div>
</div>
<div id="genaiapps" class="gen-ai-section genai-apps">
    <div>
        <h1 class="genai-titles">
            GenAI Apps
        </h1>
    </div>
    <div id="apps" class="jquery-container"></div>
</div>

<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"></script>
<script src="~/js/modernizr.custom.js"></script>
<script src="~/js/classie.js"></script>
<script src="~/js/elastic_grid.min.js"></script>
<script src="~/js/genai.js"></script>

Web Design Programming/FinalAssignment/FinalAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<article id="home-page">
    <section id="s1" class="text-center">
        <video id="background-video" autoplay="autoplay" loop muted preload="auto" poster="../media/background/bg2.jpg">
            <source src="../media/video.mp4" type="video/mp4">
        </video>
        <div class="video-cover-element"></div>
        <h1 id="home-title"> Generative AI Technology </h1>
        <span class="container">
            <p id="home-paragraph">
                Any time an AI technology is generating something on its own, it can be referred to as
                "generative AI." This umbrella term includes learning algorithms that make predictions
                as well as those that can use prompts to autonomously write articles and paint pictures.
                <br><i> Techopedia </i>
            </p>
        </span>
    </section>
    <div id="homepage-content" class="flex flex-column justify-content-between">
        <section id="s2" class="container row mx-auto content-section">
            <div class="col-md-6 col-sm-12 my-4">
                <h1>
                    GenAI Tools
                </h1>
                <p>
                    Generative AI tools refer to software or systems that use neural network techniques to
                    process and comprehend input data, subsequently producing meaningful responses.
                    <i>Scribehow</i>  <a href="Home/GenAI#genaitools" class="btn btn-outline-light"> Read More </a>
                </p>
            </div>
            <div class="col-md-6 col-sm-12 row my-4">
                <div class="col-6">
                    <img src="~/media/genaisites/bard.jpg" alt="Google Bard" class="img-fluid">
                </div>
                <div class="col-6">
                    <img src="~/media/genaisites/midjourney.jpg" alt="Midjourney" class="img-fluid">
                </div>
            </div>
        </section>
        <section id="s3" class="container row mx-auto content-section">
            <div class="col-md-6 col-sm-12 row my-4">
                <div class="col-6">
                    <img src="~/media/genaisites/google.jpg" alt="Google" class="img-fluid">
                </div>
                <div class="col-6">
                    <img src="~/media/genaisites/microsoft.jpg" alt="Microsoft" class="img-fluid">
                </div>
            </div>
            <div class="col-md-6 col-sm-12 my-4">
                <h1>
                    GenAI Organisations
                </h1>
                <p>
                    Generative AI Organizations like Microsoft, Google, Amazon and IBM have invested
                    hundreds of millions of dollars and massive compute power to build the foundational
                    models on which services like ChatGPT and others depend. <i> Gartner </i><a href="Home/GenAI#genaiorgs" class="btn btn-outline-light"> Read More </a>
                </p>
            </div>
        </section>

        <section id="s4" class="container row mx-auto content-section">
            <div class="col-md-6 col-sm-12 my-4">
                <h1>
                    GenAI Applications
                </h1>
                <p>
                    <strong>Text:</strong> GPT-3, LaMDA, LLaMA, BLOOM and GPT-4.<br />
                    <strong>Code:</strong> OpenAI Codex.<br />
                    <strong>Images:</strong> DALL-E, Midjourney and Stable Diffusion.<br />
                    <strong>Video:</strong> Make-A-Video (Meta Platforms).<br />
                    <i>Wikipedia</i> <a href="Home/GenAI#genaiapps" class="btn btn-outline-light"> Read More </a>
                </p>
            </div>
            <div class="col-md-6 col-sm-12 row my-4">
                <div class="col-6">
                    <img src="~/media/genaisites/chatgpt.jpg" alt="ChatGPT" class="img-fluid">
                </div>
                <div class="col-6">
                    <img src="~/media/genaisites/dalle.jpg" alt="Dall-E" class="img-fluid">
                </div>
            </div>
        
        </section>

        <section id="s5" class="container row mx-auto content-section">
            <div class="col-md-6 col-sm-12 row my-4">
                <div class="col-6">
                    <img src="~/media/genaisites/pie.jpg" alt="Pie Chart" class="img-fluid">
                </div>
                <div class="col-6" >
                    <img src="~/media/genaisites/job.jpg" alt="Jobs Fella" class="img-fluid">
                </div>
            </div>
            <div class="col-md-6 col-sm-12 my-4">
                <h1>
                    AI Jobs
                </h1>
                <p>
                    The prime source for jobs and talents in AI, ML, Data Science and Big Data:
                    <a href="https://ai-jobs.net/">
                        Insights AI-Jobs
                    </a><br/>
                    Python source for tables and charts:
                    <a href="https://www.kaggle.com/code/sowrabhghosh/data-science-salary-2020-22-analysis">
                        Kaggle.
                    </a>

                    <a asp-controller="Home" asp-action="GenAI" class="btn btn-outline-light"> Read More </a>
                </p>
            </div>
        </section>
        <section id="s6" class="container row m-auto text-center">
            <div class="gen-ai-websites col-12">
                <h1> List of Generative AI Websites </h1>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <p>
                            <a asp-area="" asp-controller="GenAIs" asp-action="Create"> Click here to add a new generative AI website </a>
                        </p>
                    }
                    else{
                        <p>
                        Please <a asp-area="Identity" asp-page="/Account/Login">login</a> or <a asp-area="Identity" asp-page="/Account/Register">register</a> to add a new generative AI website
                        </p>
                    }

                    if (User.Identity.IsAuthenticated)
                    {
                        <div id="genai-websites-wrapper" class="row">
                        @{
                            foreach(var i in Model)
                            {
                                <div class="col-md-2 col-sm-4 col-6">
                                    <figure>
                                        <a href="@i.AnchorLink">
                                            <img class="img-fluid" src="../images/@(i.ImageFilename + ".jpg")" />
                                            <figcaption class="fig-caption"> @i.GenAIName </figcaption>
                                        </a>
                                    </figure>
                                </div>
                            }
                        }
                        </div>
                    }
                 } 
        </section>
    </div>
</article>

<script src="~/js/home.js"></script>

Web Design Programming/FinalAssignment/FinalAssignment/Views/Home/Jobs.cshtml
@{
    ViewData["Title"] = "Jobs";
}
<link rel="stylesheet" href="~/css/jobs.css" />

<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
<py-config>
    packages = ["matplotlib", "pandas", "seaborn"]
</py-config>
<py-script>
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns
    from pyodide.http import open_url
    url = open_url('..\csv\salaries2023.csv')
    df = pd.read_csv(url)
    display(df.head(n=7), target="table", append=False)

    plt.figure(1, figsize=(9, 4))
    sns.barplot(x='work_year', y='salary_in_usd', hue='work_year', data=df)
    plt.title("Salaries")
    display(plt, target="barchart", append=False)

    plt.figure(2)
    top_jobs = df.job_title.value_counts()[: 7]
    m = df.shape[0]
    job_distribution = top_jobs*100/m
    job_distribution.plot(kind = 'pie', autopct = '%1.0f%%', figsize = (9, 4))
    plt.title('Job distribution among top 10 in demand job title')
    display(plt, target="piechart", append=False)

</py-script>

<article id="jobs-page">
    <section class="text-center">
        <div class="title-section">
        </div>
        <div class="jobs-title">
            <h1 id="jobs-title"> AI Jobs </h1>
            <p>AI job dataset: Insights AI-Jobs</p>
            <p>Python source for tables and charts: Kaggle</p>
        </div>
    </section>
    <section class="container">
        <hr />
        <section class="row gx-5">
            <div class="col-md-3 col-sm-12 col-12 jobs-content">
                <h1> Top 5 Companies </h1>
                <p><i>according to number of employees</i></p>
            </div>
            <div id="table" class="col-md-9 col-sm-12 col-12">
            </div>
        </section>
        <hr />
        <section class="row gx-5">
            <div id="piechart" class="col-md-9 col-sm-12 col-12">
            </div>
            <div class="col-md-3 col-sm-12 col-12 jobs-content">
                <h1> Job Distribution </h1>
                <p><i>among top 10 in demand job title</i></p>
            </div>
        </section>
        <hr />
        <section class="row gx-5">
            <div class="col-md-3 col-sm-12 col-12 jobs-content">
                <h1>Salaries</h1>
                <p><i>in the last 3 years</i></p>
            </div>
            <div class="col-md-9 col-sm-12 col-12">
                <div id="barchart"></div>
            </div>
        </section>
    </section>
    
</article>


<script src="~/js/jobs.js"></script>